version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      REDIS_HOST: redis  # Service name of the Redis container
      REDIS_PORT: 6379   # Default Redis port
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
